steps:
  - id: build-backend
    name: 'docker'
    args:
      - build
      - --file=Dockerfile
      - --cache-from=$_ARTIFACT_REPOSITORY_IMAGE_NAME:latest
      - .

  - name: 'docker'
    args:
      - push
      - $_ARTIFACT_REPOSITORY_IMAGE_NAME
    waitFor: ['build-backend']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - run
      - deploy
      - bizpark-scraping-server
      - --quiet
      - --image=$_ARTIFACT_REPOSITORY_IMAGE_NAME:$SHORT_SHA
      - --project=$PROJECT_ID
      - --region=$_REGION
      - --revision-suffix=$SHORT_SHA
      - --tag=latest
      - --cpu=1
      - --memory=1Gi
      - --max-instances=3
      - --min-instances=0
      - --no-use-http2 # HTTP/2での接続は行わない

substitutions:
  _REGION: by-terraform
  _ARTIFACT_REPOSITORY_IMAGE_NAME: by-terraform

# ビルドフローの中でイメージを保存し、ビルドの結果にイメージを表示する場合は、ビルド構成ファイルで Docker の push コマンドと images フィールドの両方を使用します。
images:
  - $_ARTIFACT_REPOSITORY_IMAGE_NAME:$SHORT_SHA
