steps:
  - id: build-backend
    name: 'docker'
    args:
      - build
      - --file=Dockerfile
      - '--tag=$_ARTIFACT_REPOSITORY_IMAGE_NAME:$SHORT_SHA'
      - '--tag=$_ARTIFACT_REPOSITORY_IMAGE_NAME:latest'
      - --cache-from=$_ARTIFACT_REPOSITORY_IMAGE_NAME:latest
      - .

  - id: push-backend
    name: 'docker'
    args:
      - push
      - --all-tags
      - $_ARTIFACT_REPOSITORY_IMAGE_NAME
    waitFor: ['build-backend']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - run
      - deploy
      - bizpark-scraping-server
      - --quiet
      - --image=$_ARTIFACT_REPOSITORY_IMAGE_NAME:$SHORT_SHA
      - --project=$PROJECT_ID
      - --region=$_REGION
      - --revision-suffix=$SHORT_SHA
      - --tag=latest
      - --cpu=1
      - --memory=1Gi
      - --min-instances=0
      # - --concurrency=1
      - --no-use-http2 # HTTP/2での接続は行わない
      - --set-env-vars=NEWS_SAVE_ENDPOINT=$_NEWS_SAVE_ENDPOINT
      - --set-env-vars=NODE_ENV=production
      - --update-secrets=NEWS_SAVE_ENDPOINT_ACCESS_TOKEN=NEWS_SAVE_ENDPOINT_ACCESS_TOKEN:latest

substitutions:
  _REGION: by-terraform
  _ARTIFACT_REPOSITORY_IMAGE_NAME: by-terraform
  _NEWS_SAVE_ENDPOINT: by-terraform

# ビルドフローの中でイメージを保存し、ビルドの結果にイメージを表示する場合は、ビルド構成ファイルで Docker の push コマンドと images フィールドの両方を使用します。
images:
  - $_ARTIFACT_REPOSITORY_IMAGE_NAME:$SHORT_SHA
