version: '3.8'
services:
  scraping_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scraping_server
    networks:
      - bizpark-scraping
    ports:
      - 3000:3000

networks:
  bizpark-scraping:
    driver: bridge
