version: '3.8'
services:
  scraping_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scraping_server
    environment:
      NODE_ENV: development
    networks:
      - bizpark-scraping
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000

networks:
  bizpark-scraping:
    driver: bridge
